name: Azure Resource Group Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_RESOURCEGROUP_NAME: ToyWebsite
      LOCATION: eastus
      ENVIRONMENT: nonprod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set working directory
        run: cd ${{ github.workspace }}/actions/bicep

      - name: Debug
        run: |
          pwd
          ls -R

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}

      - name: Create Resource Group and Deploy Resources
        run: |
          az group create --name $AZURE_RESOURCEGROUP_NAME --location $LOCATION
          az deployment group create --resource-group $AZURE_RESOURCEGROUP_NAME --template-file 'strorage.bicep' --parameters @parameters-$ENVIRONMENT.json
