name: Azure Resource Group Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_RESOURCEGROUP_NAME: ToyWebsite
      LOCATION: eastus
      ENVIRONMENT: nonprod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}

      - name: Create Resource Group and Deploy Resources
        run: |
          # Uncomment the following line for actual deployment
           az deployment group create --resource-group Newresource --template-file './actions/bicep/strorage.bicep'
