name: Azure Resource Group Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_RESOURCEGROUP_NAME: newtesriyas
      LOCATION: eastus
      ENVIRONMENT: nonprod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}

      - name: Create Resource Group and Deploy Resources
        run: |
             az group create --name $AZURE_RESOURCEGROUP_NAME --location $LOCATION

      - name: Azure CLI 
        uses: azure/arm-deploy@v1
        with:
          deploymentName: ${{ github.run_number }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          template: ./actions/bicep/strorage.bicep
          parameters: environmentType=${{ env.ENVIRONMENT }}
